# Generated by Django 2.1.7 on 2019-03-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=15, verbose_name='número de documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
            ],
        ),
    ]
