# Generated by Django 2.1.7 on 2019-03-25 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('propietarios', '0002_auto_20190324_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoPropietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Modelo')),
            ],
        ),
        migrations.AlterField(
            model_name='propietario',
            name='soporte_documento',
            field=models.FileField(help_text='Cargue el soporte de su documento en: PDF, JPG o PNG', upload_to='propietarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='vehiculopropietario',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietarios.Propietario'),
        ),
    ]
