# Generated by Django 2.1.7 on 2019-03-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0003_auto_20190324_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculopropietario',
            options={'verbose_name': 'Vehiculo del propietario', 'verbose_name_plural': 'Vehiculos del propietario'},
        ),
        migrations.AddField(
            model_name='vehiculopropietario',
            name='placa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
