# Generated by Django 2.1.7 on 2019-03-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_tipo'),
        ('propietarios', '0004_auto_20190325_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculopropietario',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Tipo'),
            preserve_default=False,
        ),
    ]
