# Generated by Django 2.1.7 on 2019-03-25 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0005_vehiculopropietario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculopropietario',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculopropietario',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='propietarios.Propietario'),
        ),
    ]
